### ISSUE TITLE
allow setting pool cidrs with netmask

### ISSUE THREAD

**Issue by drewmullen** [aws-ia/terraform-aws-ipam#15]
AWS Console uses `preview` to allow users to set a range for their next pool cidr vs explicitly setting. Try injecting `preview_ipam_pool_cidr` data source conditionally into the `sub_pool` sub-module. This will require making `cidrs` optional and adding `netmask_length` & `disallowed_cidrs`.

validation on the variable should also confirm the sub_pool _does NOT_ have both `cidrs` and `netmask_length`

**Comment by sundar-shanmugam** [comment]
Tried changing the sub_pool module to include data/resource types of `aws_vpc_ipam_preview_next_cidr` to generate CIDRs based on `netmask_length`; however, sending a parallel map of objects results in duplicate/overlapping CIDRs causing issues. I tried adding `depends_on` and also `time_sleep` but since we loop through the objects map; they don’t make any difference.
```
resource "aws_vpc_ipam_preview_next_cidr" "sub" {
  count = var.pool_config.cidr == null ? 1 : 0

  ipam_pool_id   = var.source_ipam_pool_id
  netmask_length = var.pool_config.netmask_length[0]

  disallowed_cidrs = [
    "172.2.0.0/32"
  ]
}
```
```
resource "aws_vpc_ipam_pool_cidr" "sub" {
  for_each = var.pool_config.cidr == null ? toset(var.pool_config.netmask_length) : toset(var.pool_config.cidr)

  ipam_pool_id = aws_vpc_ipam_pool.sub.id
  cidr         = var.pool_config.cidr == null ? aws_vpc_ipam_preview_next_cidr.sub[0].cidr : each.key

  dynamic "cidr_authorization_context" {
    for_each = var.pool_config.cidr_authorization_context == null ? {} : var.pool_config.cidr_authorization_context
    content {
      message   = cidr_authorization_context.message
      signature = cidr_authorization_context.signature
    }
  }

  depends_on = [
    aws_vpc_ipam_preview_next_cidr.sub
  ]
}
```
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/77040607/156287557-a8d0d2af-58f2-42e6-a90c-31481975e158.png">

**Comment by drewmullen** [comment]
Upon further investigation, we can get preview to work but because the call is region specific we cannot `preview` cidrs outside the ipam main region

**Comment by drewmullen** [comment]
furthermore, module objects (looped) are created in parallel. notice both get `10.1.0.0/28`:
```
module.basic.module.level_two["us-east-1/team_netmask"].aws_vpc_ipam_pool.sub: Creating...
module.basic.module.level_two["us-east-1/team_netmask2"].aws_vpc_ipam_pool.sub: Creating...
module.basic.module.level_two["us-east-1/team_netmask2"].data.aws_vpc_ipam_preview_next_cidr.sub[0]: Read complete after 1s [id=10.1.0.0/28_ipam-pool-08aa0a7b6edc55558]
module.basic.module.level_two["us-east-1/team_netmask"].data.aws_vpc_ipam_preview_next_cidr.sub[0]: Read complete after 1s [id=10.1.0.0/28_ipam-pool-08aa0a7b6edc55558]
```

**Comment by drewmullen** [comment]
Included a temporary branch with an example of calculting subnets: https://github.com/aws-ia/terraform-aws-ipam/blob/subnet_calc/examples/basic/main.tf

this is pretty verbose, it may be worth writing an alternative version of the subnet calculator to handle an input thats more similar to the `pool_configurations` input
