### ISSUE TITLE
not able to set the locale in sub_pools.

### ISSUE THREAD

**Issue by weslleycamilo** [aws-ia/terraform-aws-ipam#32]
Hey guys..

i have been trying to define the locale in a 3nd level and it is not working.. all the pools with with no locale. I read in the doc that i would define it and all the child would get the same as i cant change it later.

I am able to define in the 2nd level as it was before but not my planned architecture pools.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/19431474/163214659-f2ce1edc-482c-4834-a048-f3febafb6d51.png">

![image](https://user-images.githubusercontent.com/19431474/163214906-55c58199-fbcb-4136-90b9-7baedc0c539a.png)

would it be an issue ? 

is there any suggestion?

**Comment by drewmullen** [comment]
Not sure how I missed this issue..
 I'll take a look asap, it should definitely work in the 3rd layer

Sorry for the delay!

**Comment by drewmullen** [comment]
i confirmed the behavior. definitely a bug! thank you for reporting.
