### ISSUE TITLE
Upgrading to 1.1.3 breaks applies with an InvalidParameterCombination error

### ISSUE THREAD

**Issue by devops-flipsidecrypto** [aws-ia/terraform-aws-ipam#40]
Given the changeset:

``` 
# module.ipam.module.level_zero.aws_vpc_ipam_pool.sub will be updated in-place
  ~ resource "aws_vpc_ipam_pool" "sub" {
        id                       = "ipam-pool-0a0b53587b6f4f8dd"
      ~ tags                     = {
          + "Name" = ""
        }
      ~ tags_all                 = {
          + "Name" = (known after apply)
        }
        # (10 unchanged attributes hidden)
    }

Plan: 0 to add, 6 to change, 0 to destroy.
```

The following error is returned:

module.ipam.module.level_zero.aws_vpc_ipam_pool.sub: Modifying... [id=ipam-pool-0a0b53587b6f4f8dd]
╷
│ Error: error updating IPAM Pool (ipam-pool-0a0b53587b6f4f8dd): InvalidParameterCombination: The request must contain a modification to the ipam pool.
│ 	status code: 400, request id: 368e2a77-d794-435f-a4b2-775ab9f73844
│
│   with module.ipam.module.level_zero.aws_vpc_ipam_pool.sub,
│   on .terraform/modules/ipam/modules/sub_pool/main.tf line 12, in resource "aws_vpc_ipam_pool" "sub":
│   12: resource "aws_vpc_ipam_pool" "sub" {
│
╵

Could relate to https://github.com/aws-ia/terraform-aws-ipam/issues/38

**Comment by drewmullen** [comment]
Thanks for reporting this. taking a look now

**Comment by drewmullen** [comment]
Hi @devops-flipsidecrypto 

issue was auto closed by the PR - if you remember, would appreciate a message back confirming this fixed your issue! Thanks and apologies about that. the issue only appeared on pre-built ipams looking to upgrade. our testing currently only builds new then destroys each time. i took a note that theres an opportunity to improve our testing to do a:

build previous release -> `terraform init -upgrade` to latest -> validate no bugs
