### ISSUE TITLE
aws_ram_resource_share.sub[0] name is changed to an invalid name

### ISSUE THREAD

**Issue by txsutton** [aws-ia/terraform-aws-ipam#49]
After upgrading from 1.1.4 to 1.1.5 we noticed that the aws_ram_resource_share.sub[0] name is changed which causes the terraform apply to fail.

The name is changed from us-east-2-level1 to us-east-2/level1 which is invalid

│ Error: Error creating RAM resource share: InvalidParameterException: Resource share name can contain only alphabetic characters, numbers, spaces, periods, and dashes.
│
│   with module.this.module.ipam.module.level_two["us-east-2/level1"].aws_ram_resource_share.sub[0],
│   on .terraform\modules\this.ipam\modules\sub_pool\main.tf line 45, in resource "aws_ram_resource_share" "sub":
│   45: resource "aws_ram_resource_share" "sub" {

**Comment by drewmullen** [comment]
Thanks for reporting. does reverting the version resolve your immediate issue?

**Comment by drewmullen** [comment]
can you share the pool_config from that level - **please do not include any ram share principal values**

I think it may just be a issue related to how the description (or implied description) is defined

**Comment by drewmullen** [comment]
i see what the issue is. a bug was introduced in 1.1.5, ill resolve shortly - thanks for reporting
