### ISSUE TITLE
Terraform output Pool arn/ids

### ISSUE THREAD

**Issue by jimsmith** [aws-ia/terraform-aws-ipam#57]
Hello,

Thanks for this terraform module, can you please have the output of pool ids as well as these are more meaningful when passing these to different teams/projects.

I'm already using `pool_names` but can really be doing with the `pool_ids` alongside pool names.

**Comment by jimsmith** [comment]
output "pools_information_level_1" {
  description = "List of pool information. (level 1)"
  value = {
    for key in keys(module.ipv4_scope.pools_level_1) :
      key => {
        arn = module.ipv4_scope.pools_level_1[key].arn
        id = module.ipv4_scope.pools_level_1[key].id
        ipam_scope_id = module.ipv4_scope.pools_level_1[key].ipam_scope_id
        ipam_scope_type = module.ipv4_scope.pools_level_1[key].ipam_scope_type
      }
  }
}

**Comment by drewmullen** [comment]
For teams consuming from a pool they can also use a data source to search for the pool vs handing them the ID

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/vpc_ipam_pool

**Comment by jimsmith** [comment]
Excellent thanks for that @drewmullen I'll close this issue as it's no longer an issue (thanks!)
