### ISSUE TITLE
Feature: Define `cidr_authorization_context` blocks for each public CIDR

### ISSUE THREAD

**Issue by SeanBickle** [aws-ia/terraform-aws-ipam#58]
Background
------------

AWS IPAM pools can contain multiple CIDRs. An authorization context must be defined for each public CIDR in a pool.

This module supports multiple CIDRs per pool, but only one `top_cidr_authorization_context`.

It is therefore not possible to expand the capacity of a public pool using this module.

Proposed Feature
------------------

This could be resolved by introducing a new `top_cidr_authorization_contexts` variable. In time, this could supersede the existing `top_cidr_authorization_contexts`. For example:

```
top_cidr = ["<public-cidr-a>", "<public-cidr-b>"]
top_cidr_authorization_contexts = [
  {
    cidr      = "<public-cidr-a>"
    message   = "<message>"
    signature = "<signature>"
  },
  {
    cidr      = "<public-cidr-b>"
    message   = "<message>"
    signature = "<signature>"
  }
]
```

Within the `sub_pool` module, this can be transformed into a mapping keyed on the CIDR. Then, for each CIDR in the `aws_vpc_ipam_pool_cidr.sub` resource, lookup the corresponding authorization context.

**Comment by drewmullen** [comment]
Hi! thanks for opening this issue. I believe you should be able to add them to specific sub pools. Its an optional parameter in the var that is passed:

https://github.com/aws-ia/terraform-aws-ipam/blob/main/modules/sub_pool/variables.tf#L20C22-L20C22

Please let me know if I'm missing your question here if there is any issue!

**Comment by drewmullen** [comment]
Thank you for the additional context. 🤔 hmm yes this does seem to be a gap. `cidr`s can only have [1 context](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/ipam_pool_cidr.go#L62) but i didnt consider that you might have **multiple public cidrs** to add

SO trouble is that we either perform a breaking change or add a confusing 2nd variable with a similar name. im tempted with the former where we'd use your proposed `list(map(string))` then just cut a new major release... technically it would be breaking but public ip usage is less common so the upgrade document would likely be pretty small

Question for you, @SeanBickle - so the way i read the docs it seems like you **should not** ever pass the `cidr_authorization_context` to sub pools (non top level). do you agree? if thats the case that should also be removed from: 
- https://github.com/aws-ia/terraform-aws-ipam/blob/main/modules/sub_pool/variables.tf#L20C22-L20C22

Proposed change:
- breaking: change `top_cidr_authorization_context` to `top_cidr_authorization_contexts` using the object type mentioned above
- remove cidr_context from [pool_config](https://github.com/aws-ia/terraform-aws-ipam/blob/main/modules/sub_pool/variables.tf#L20C22-L20C22)
- adjust logic in [local](https://github.com/aws-ia/terraform-aws-ipam/blob/991dcf02fd2175bd3a6b10a4ee61b01cf89f813d/modules/sub_pool/main.tf#L10C109-L10C109)

**Comment by SeanBickle** [comment]
> SO trouble is that we either perform a breaking change or add a confusing 2nd variable with a similar name. im tempted with the former where we'd use your proposed list(map(string)) then just cut a new major release... technically it would be breaking but public ip usage is less common so the upgrade document would likely be pretty smal

I had also considered suggesting making the `top_cidrs` variable a list of objects (or mappings?) instead of a list of strings to simplify the module inputs and de-duplicate some of this information. For example:

```
variable "top_cidr" {
  description = "Top-level CIDR blocks."
  type        = list(object({
    cidr = string,
    authorization_context = optional(object({
      message = string,
      signature = string
    }))
  })
}
```

But this is an even more intrusive breaking change, so perhaps this separate variable is preferable.

> Question for you, @SeanBickle - so the way i read the docs it seems like you should not ever pass the cidr_authorization_context to sub pools (non top level). do you agree?

From an AWS perspective, this is correct -- the CIDR authorization context is only ever needed for top-level pools.

> if thats the case that should also be removed from:
> 
> * https://github.com/aws-ia/terraform-aws-ipam/blob/main/modules/sub_pool/variables.tf#L20C22-L20C22

I don't think this is possible, as [the top-level pool is technically also an instance of the `sub_pool` module](https://github.com/aws-ia/terraform-aws-ipam/blob/main/main.tf#L43).

Instead, maybe some validation can be added to the `sub_pool` module to check if `source_ipam_pool_id` is set? If it is, ensure that `cidr_authorization_context` has not been set.

**Comment by drewmullen** [comment]
Yeah, in a perfect world we would update the whole top_cidr... hmm

> I don't think this is possible, as [the top-level pool is technically also an instance of the sub_pool module](https://github.com/aws-ia/terraform-aws-ipam/blob/main/main.tf#L43).

yes but funny enough i define that outside the `pool_config` var for some reason: https://github.com/aws-ia/terraform-aws-ipam/blob/main/main.tf#L54 ... I probably ran into this problem when testing, trying to set at the child level... but never realized that the functionality is completely unavailable in child pools

I'd like to take a day or so to think about whether we should use this breaking change to, as you suggested, update the `top_cidr` or merely just add a new resource.

The purest in me wants to align it in the DRYest way, updating `top_cidr`. But that will take more time due to:
- increased complexity on change to tf module
- increase risk on breaking existing deployments (requires more testing)
- more changes for users without public IPs (majority of our users)

Curious what your vote is after considering this as well @SeanBickle & @pablo19sc (happy to talk offline if youre available)

**Comment by drewmullen** [comment]
@SeanBickle i have no way of testing this atm. any chance you mind giving this a shot?

**Comment by SeanBickle** [comment]
> Curious what your vote is after considering this as well @SeanBickle 

As you mention, updating `top_cidr` would be the most DRY approach, so I think I would favour this long-term, but I appreciate the concerns with breaking changes that would (perhaps unfairly) affect 99% of users.

On that topic: if there is a chance that this change to `top_cidr` is preferable long-term and therefore might be implemented in the future anyway, then it would actually cause less disruption to introduce it now. Otherwise, BYOIP users will have to reconcile the introduction of `top_cidr_authorization_contexts` in the short term, but then _all_ users would have to reconcile the changes to `top_cidr` in the long-term, including BYOIP users.

> @SeanBickle i have no way of testing this atm. any chance you mind giving this a shot? https://github.com/aws-ia/terraform-aws-ipam/pull/59

Sure, I'll try it out and report back, thanks!

**Comment by SeanBickle** [comment]
@drewmullen I created a quick test module locally, sourcing your remote branch. Seems to work well!

I defined a couple of top-level public CIDRs and an authorization context for each. Both CIDRs were added to the single top-level pool. I could also deprovision one CIDR, or both CIDRs, without any issues.

```
module "ipam_pools" {
  source = "git@github.com:drewmullen/terraform-aws-ipam.git/?ref=58-multi-public-cidr"
  providers = { aws = aws.ipam }

  create_ipam     = false
  ipam_scope_id   = "<existing-public-scope-id>"
  ipam_scope_type = "public"

  top_cidr = ["<cidr-a>", "<cidr-b>"]
  top_cidr_authorization_contexts = [
    {
      cidr      = "<cidr-a>"
      message   = "<message-a>"
      signature = "<signature-a>"
    },
    {
      cidr      = "<cidr-b>"
      message   = "<message-b>"
      signature = "<signature-b>"
    }
  ]
}
```

**Comment by drewmullen** [comment]
Thanks for the feedback and candid thoughts!

I think we will move forward with the implementation in the PR. There are several reasons to move the login into a more complex `top_cidr` but the impact to existing users both in changing HCL and potentially introducing unintended drift is greater than the DRY gain, imo. I'll ask the IA team to move forward with this PR asap.

Again, thanks for opening this issue, hashing it out with me, and for testing the fix!

**Comment by SeanBickle** [comment]
No problem, and thanks for rapidly resolving this issue! This will be very useful.
