### ISSUE TITLE
Configuring IPAM Pools for IPv4 and IPv6 in the Same Module

### ISSUE THREAD

**Issue by robodorm** [aws-ia/terraform-aws-ipam#61]
We are currently facing an issue while trying to configure IPAM (IP Address Management) pools for both IPv4 and IPv6 within a single module. We have encountered errors that suggest mixing IPv4 and IPv6 scopes may not be supported. To help us resolve this issue, we kindly request your assistance in providing a basic example demonstrating how to successfully configure IPAM pools for both IPv4 and IPv6 within the same IPAM module.

Our objective is to create IPAM pools for both IPv4 and IPv6 addresses within a single IPAM module because, as per our understanding, AWS allows only one [IPAM per Region](https://docs.aws.amazon.com/vpc/latest/ipam/quotas-ipam.html) to be used.

To clarify our request further, we are looking for a basic module usage example that illustrates how to configure the IPAM module to provide two separate scopes for IPv4 **and** IPv6 addresses.

Currently in examples we can see how to use IPv4 **or** IPv6. Maybe you could update the [multiple scopes example](https://github.com/aws-ia/terraform-aws-ipam/blob/main/examples/multiple_scopes/main.tf) to add IPv6 as well?

Thank you for your assistance.

**Comment by drewmullen** [comment]
Hi, thanks for opening this issue. IPAM uses several concepts that you can review [here](https://docs.aws.amazon.com/vpc/latest/ipam/how-it-works-ipam.html)

The way this module is designed you would have 2 invocations. 1st invocation creates the ipam, default scopes, then pools for either ipv4 or 6. the 2nd invocation would **not** create ipam but would reference the scope from the 1st instantiation. You'd then create pool structures for the other type (ipv6 if your 1st was ipv4, etc). You can see an example of referencing an ipam created in another instantiation here: https://github.com/aws-ia/terraform-aws-ipam/blob/main/examples/multiple_scopes/main.tf#L58-L59

Hope this helps!

**Comment by drewmullen** [comment]
Hi @robodorm did this answer your question?

**Comment by artem-collectai** [comment]
Hello, I'm a colleague of @robodorm and just wanted to let you know that we've abandoned the idea of using IPAM v6 pools because we realized that https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipam_pool_cidr_allocation only supports IPv4.

**Comment by artem-collectai** [comment]
I gave it another try but it looks like this TF module supports only BYOIP IPv6 pools: `top_cidr` is a required argument, but if I provide it as an empty list, I get the following error:

<img width="674" alt="image" src="https://github.com/aws-ia/terraform-aws-ipam/assets/108511527/b3c008ff-cdc9-485c-b107-e8ed47af2e6a">

**Comment by drewmullen** [comment]
ipv6 can only be specified at the top level iirc

**Comment by artem-collectai** [comment]
Yes, we specified the address family:

```terraform
module "this6" {
  source  = "registry.terraform.io/aws-ia/ipam/aws"
  version = "~> 2.0.0"

  top_netmask_length = 52

  ipam_scope_id   = module.this.ipam_info.public_default_scope_id
  ipam_scope_type = "public"

  create_ipam = false

  top_name       = "global ipam 6"
  address_family = "ipv6"

  pool_configurations = {
    corporate-eu6 = {
      locale = "eu-central-1"
      aws_service = "ec2"

      sub_pools = {
        sandbox = {
          name                 = "sandbox-dev-6"
          netmask_length       = 56
          ram_share_principals = [local.ou_sandbox]
          locale               = data.aws_region.current.name

          sub_pools = {
            eks-sandbox-6 = {
              netmask_length       = 64
              ram_share_principals = [local.ou_sandbox]
              locale               = data.aws_region.current.name
            }
          }
        }
      }
    }
  }
}
```

**Comment by drewmullen** [comment]
> only BYOIP IPv6 pools

failed to read this. yes initially this was written for byoip... i would have to think about how to use aws provided... might not be too hard. 

can you please open a feature request and include your HCL example

**Comment by robodorm** [comment]
Many thanks for support!
