### ISSUE TITLE
Feature request: support IPv6 pools with Amazon-owned CIDRs

### ISSUE THREAD

**Issue by artem-collectai** [aws-ia/terraform-aws-ipam#63]
Currently the following doesn't work because `top_cidr` is required, but conflicts with netmask_length:

```terraform
module "this6" {
  source  = "registry.terraform.io/aws-ia/ipam/aws"
  version = "~> 2.0.0"

  top_netmask_length = 48

  # scope ID created by another instantiation of this module for an IPv4 pool
  ipam_scope_id   = module.this.ipam_info.public_default_scope_id
  ipam_scope_type = "public"

  create_ipam = false

  top_name       = "global ipam 6"
  address_family = "ipv6"

  pool_configurations = {
    corporate-eu6 = {
      locale = "eu-central-1"
      aws_service = "ec2"

      sub_pools = {
        sandbox = {
          name                 = "sandbox-dev-6"
          netmask_length       = 52
        }
      }
    }
  }
}
```

**Comment by drewmullen** [comment]
Thanks for opening this feature request. I will definitely consider how to implement this

**Comment by drewmullen** [comment]
One issue I may have with properly implementing this feature is that I don't have a BYOIP for me to test and verify no breaking changes are caused as a side effect. 

I'm sorry to call you out directly but, @SeanBickle you had used this module before using [byoip ipv6](https://github.com/aws-ia/terraform-aws-ipam/issues/58). If i code in this feature would you be able to test a feature branch with a `plan` to validate no unintended changes are caused? 😅
